"""update client organization relationship

Revision ID: acf4c020f63c
Revises: 4ea4629c7f95
Create Date: 2026-07-12 15:44:38.139440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf4c020f63c'
down_revision: Union[str, Sequence[str], None] = '4ea4629c7f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clients', 'organizations', ['organization_id'], ['id'])
    op.alter_column('employees', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('employees', 'hire_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'hire_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employees', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'organization_id')
    # ### end Alembic commands ###
